import { evidenceIndex } from "../models/evidence.js";
import type { AccountResearch } from "../models/research.js";

/**
 * The account timeline is where a rep actually looks, so the note has to read
 * like something a colleague left: what we saw, what it might mean, where to
 * check it, and how to open the conversation. Properties hold the structured
 * fields; this holds the story.
 *
 * HubSpot renders a note body as rich text, so light HTML is used for
 * structure. Nothing here is a claim the research did not make.
 */

/** HubSpot's documented ceiling is 65,536 characters; a readable note is far shorter. */
const MAX_BODY = 12_000;

export function buildTimelineNote(research: AccountResearch): string {
  const index = evidenceIndex(research.evidence);
  const parts: string[] = [];
  const scanned = research.finishedAt.slice(0, 10);

  parts.push(
    `<p><b>ABMBuddy research — ${escapeHtml(research.company.name)}</b><br>` +
      `<i>${escapeHtml(scanned)} · ${research.evidence.length} public sources` +
      `${research.product ? ` · positioned around ${escapeHtml(research.product.name)}` : ""}</i></p>`,
  );

  const initiatives = research.extraction.strategicInitiatives.slice(0, 3);
  if (initiatives.length) {
    parts.push(
      `<p><b>Publicly stated initiatives</b></p><ul>${initiatives
        .map((item) => `<li>${escapeHtml(item.statement)}</li>`)
        .join("")}</ul>`,
    );
  }

  if (research.signals.length) {
    parts.push(
      `<p><b>Signals observed</b></p><ul>${research.signals
        .slice(0, 5)
        .map(
          (signal) =>
            `<li>${escapeHtml(signal.name)} (${pct(signal.confidence)}%) — ${escapeHtml(signal.description)}</li>`,
        )
        .join("")}</ul>`,
    );
  }

  const top = research.hypotheses[0];
  if (top) {
    parts.push(
      `<p><b>Possible bottleneck: ${escapeHtml(top.title)} (${pct(top.confidence)}% confidence)</b><br>` +
        `${escapeHtml(top.hypothesis)}</p>`,
    );
    parts.push(
      `<p><i>Reasoning:</i> ${escapeHtml(top.reasoning.observedChange)} → ` +
        `${escapeHtml(top.reasoning.operationalImplication)} → ` +
        `${escapeHtml(top.reasoning.potentialBottleneck)}</p>`,
    );
    if (top.validationQuestions.length) {
      parts.push(
        `<p><b>Worth asking</b></p><ul>${top.validationQuestions
          .map((question) => `<li>${escapeHtml(question)}</li>`)
          .join("")}</ul>`,
      );
    }

    // Sources are the point: anything above can be checked in one click.
    const sources = top.evidenceIds
      .map((id) => index.get(id))
      .filter((item): item is NonNullable<typeof item> => Boolean(item))
      .slice(0, 5);
    if (sources.length) {
      parts.push(
        `<p><b>Evidence</b></p><ul>${sources
          .map(
            (item) =>
              `<li><a href="${escapeAttr(item.url)}">${escapeHtml(truncate(item.title, 90))}</a>` +
              ` <i>(${escapeHtml(item.sourceType)})</i></li>`,
          )
          .join("")}</ul>`,
      );
    }
  }

  if (research.stakeholders?.stakeholders.length) {
    parts.push(
      `<p><b>Who to talk to</b></p><ul>${research.stakeholders.stakeholders
        .slice(0, 4)
        .map((person) => {
          const who = person.name ?? person.title ?? "Unnamed role";
          const title = person.name && person.title ? `, ${person.title}` : "";
          return `<li>${escapeHtml(who + title)} — ${escapeHtml(person.role.replace(/_/g, " "))}: ${escapeHtml(
            person.rationale,
          )}</li>`;
        })
        .join("")}</ul>`,
    );
  }

  if (research.strategy) {
    parts.push(
      `<p><b>Suggested approach</b><br>${escapeHtml(research.strategy.summary)}<br>` +
        `<i>Start with:</i> ${escapeHtml(research.strategy.entryPoint.who)} — ${escapeHtml(
          research.strategy.entryPoint.rationale,
        )}</p>`,
    );
  }

  if (research.outreach) {
    parts.push(
      `<p><b>Opener</b><br>${escapeHtml(research.outreach.conversationOpener)}</p>` +
        `<p><i>Suggested subject: ${escapeHtml(research.outreach.subject)}</i></p>`,
    );
  }

  // Hypotheses are possibilities; the note should say so where a reader sees it.
  parts.push(
    `<p><i>Generated by ABMBuddy from public sources. Bottlenecks are hypotheses to validate, ` +
      `not established facts.</i></p>`,
  );

  const body = parts.join("");
  return body.length <= MAX_BODY ? body : `${body.slice(0, MAX_BODY - 12)}…</p>`;
}

function pct(confidence: number): number {
  return Math.round(Math.max(0, Math.min(1, confidence)) * 100);
}

function truncate(text: string, max: number): string {
  const clean = text.replace(/\s+/g, " ").trim();
  return clean.length <= max ? clean : `${clean.slice(0, max - 1)}…`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeAttr(value: string): string {
  return escapeHtml(value).replace(/'/g, "&#39;");
}
